# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = 'cab440cc596ef841212ee34cbb2acfdb'
  config.secret_key = '4d17b084e72bbfea2d7d853d8fad5a73'
  config.default_from = 'nicolaszissou75@hotmail.com'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
